### ISSUE TITLE
Create 'Exit and resume survey' buttons for all surveys

### ISSUE THREAD

**Issue by gilliankerr** [LogicalOutcomes/SIS-LimeSurvey#10]
DUE: Wednesday
The basic survey template should have exit and resume buttons. This will apply both to the LogicalOutcomes template and to the OrgWise template. Those templates are the only ones we will be using for all surveys.

**Comment by trivender** [comment]
I tried several ways to exit/save links at the top bar but they do not not align well/look consistent across different device screens. I will try to add them in top bar in future but for now I have decided to keep the at button (as in TFR template by defalut) . Test link: http://logicaloutcomes.net/forms/index.php/828918?newtest=Y

**Comment by gilliankerr** [comment]
This solution is fine - let's keep it at the bottom. I didn't realize that was the default.

**Comment by gilliankerr** [comment]
good to close
