### ISSUE TITLE
Reposition 'Strongly disagree' and 'agree' statements in Managers Feedback Survey

### ISSUE THREAD

**Issue by gilliankerr** [LogicalOutcomes/SIS-LimeSurvey#12]
In Managers Feedback Survey, position 'Strongly Disagree' and Strongly Agree' to be at the far left and far right of the slider. For example:
My manager gives me actionable feedback that helps me improve my performance. | Strongly Disagree | Strongly Agree
from http://logicaloutcomes.net/forms/index.php/154199?lang=en

**Comment by mmirasol** [comment]
Fixed. You need to specify a Slider left/right text separator under Advanced Settings.  In this case, we specify: |
