### ISSUE TITLE
Fix theme: welcome page and progress bar 

### ISSUE THREAD

**Issue by saragaudon** [LogicalOutcomes/SIS-LimeSurvey#13]
For the main theme
1. Revisit the welcome page/Question 1, and set up image/welcome page so that it can be edited (from admin sign), as discussed with Gillian and Sara
2. Add progress bar and numbered pages (as discussed with Sara)

Check with Gillian & Sara.

**Comment by mmirasol** [comment]
I already put in the content for #1.  Please have a look:
http://logicaloutcomes.net/forms/index.php/886367?newtest=Y

**Comment by mmirasol** [comment]
for #2, it looks like the template is buggy. It hides the progress bar even though it is enabled in the survey settings.  to make it display, we need to put in a few lines of javascript.  will have this done shortly.

**Comment by mmirasol** [comment]
#2 is done as well. please test.
http://logicaloutcomes.net/forms/index.php/886367?newtest=Y&lang=en
in case the progress bar does not show, please clear cache first to reload the js files.

**Comment by mmirasol** [comment]
sorry clunky means crowded? unfortunately there is no wider progress bar.  this is the one included in the template.  we can definitely make changes to it but i think it was made like this for mobile display.  we can get rid of the text or the bar if you prefer.

**Comment by gilliankerr** [comment]
Let's not do custom development on this... How about removing the bar and just keeping the text? 
![image](https://cloud.githubusercontent.com/assets/4176201/26653587/84e44cfe-4621-11e7-85f5-94e7fa4ed5d8.png)

I do think that surveys look much more inviting if they have an image on the welcome page, like the orgwise surveys do.

**Comment by mmirasol** [comment]
sara requested to remove the image. the old question is still there, just hidden. i will apply the requested to text to that and just restore it for now and we hide the bar.

**Comment by mmirasol** [comment]
@saragaudon, @gilliankerr said: we will have 2 templates: 
1. For SIS/OCASI 
2.For LogicalOutcomes/DHIS2 consultants list. 

We already prepared the blue template for LogicalOutcomes.
http://logicaloutcomes.net/forms/index.php/667418?newtest=Y, 

Should we create a similar template for SIS and apply it to this survey? Or are you good with the current one? 
http://logicaloutcomes.net/forms/index.php/886367?newtest=Y&lang=en

**Comment by saragaudon** [comment]
Thanks @mmirasol I think the two templates you have are looking good - can both have just the progress bar / not the line of text? After the progress bar fix, and logo (below) I'm satisfied. 

I'm going to send you an email with our new logo file - if you can replace the logo image. Thanks!

**Comment by mmirasol** [comment]
ok will remove the text and replace the logos in both.

**Comment by mmirasol** [comment]
hi sara. just replaced the logos in both themes.
progress bar updated for both as well.
please check.
http://logicaloutcomes.net/forms/index.php/667418?newtest=Y
http://logicaloutcomes.net/forms/index.php/886367?newtest=Y

the new logical outcome theme is currently used in a test survey test_template_lo(ID:667418),
should we apply it to LogicalOutcomes Independent Contractor Agreement(ID:252826) and test again?

**Comment by saragaudon** [comment]
Thanks Mark, progress bar looks better, thanks for sharing the two themes.

@mmirasol  you can apply LO theme to the contractor agreement. Can you name the themes so we know, like 'OCASI green template' or something? 'LO blue theme'...? You can suggest. 

@gilliankerr  I'm happy with these two  - do you have anything more to add? If not, please close this / or I can later.

**Comment by mmirasol** [comment]
@saragaudon you can apply LO theme to the contractor agreement. Can you name the themes so we know, like 'OCASI green template' or something? 'LO blue theme'...? You can suggest. 
> already done.

**Comment by mmirasol** [comment]
footer has been removed from all LO templates.
and the DHIS2 still has the old lo template no progress bar.
and the logical outcome survey now has the new template LO-standard which is the blue theme with the progress bar
all orgwise surveys + sis survey now have the new template OCASI-standard assigned which is the green theme with the progress bar.
please confirm if this is correct.
the names LO-standard and OCASI-standard were given by Gillian.

**Comment by saragaudon** [comment]
Hi Mark - on the OCASI-standard theme, after the intro page there is still this Question index thing appearing at bottom, can this be removed? 
(I'm looking at page 2 of the SIS survey)
![image](https://cloud.githubusercontent.com/assets/15642297/26732120/7b746b54-4784-11e7-8b2c-d78af60f4122.png)

**Comment by saragaudon** [comment]
(I was viewing in French mode, in English it's the 'Question Index' )

**Comment by mmirasol** [comment]
noted sara, will check it.

**Comment by mmirasol** [comment]
This error was being caused by the setting for Show question index / allow jumping setting.
![image](https://cloud.githubusercontent.com/assets/13954274/26750815/b1fcf22a-485d-11e7-94c3-8058b2f513e3.png)

Do you need to see the list of questions at the bottom of the page?
If not, then turning this off will get rid of the error.
In addition, should the survey display each page by group or by question? Please confirm.  Thanks.

**Comment by mmirasol** [comment]
The survey is currently set to display Group by Group and the Show question index is disabled so the error is gone.  Please confirm if the survey runs as expected.

**Comment by saragaudon** [comment]
Thanks Mark. We don't need to see list of questions at bottom of page. I think re: display of group or question, it really depends on the survey design...I don't see the Question index any more, thank you!

**Comment by mmirasol** [comment]
happy to help. =)
