### ISSUE TITLE
Create 5 one-page surveys as ending pages for the 5 OrgWise surveys

### ISSUE THREAD

**Issue by gilliankerr** [LogicalOutcomes/SIS-LimeSurvey#14]
Create 5 new surveys that will replace the ending page for each instrument. We want 3 sections for each instrument 
- some content (see links below)
- a link to one or two resources for people to find out more
- a brief poll asking whether they think it would be useful

The content of each page is here: 
https://sites.google.com/view/orgwise/understanding-your-results/manager-feedback-survey.
https://sites.google.com/view/orgwise/understanding-your-results/partner-self-assessment-tool
https://sites.google.com/view/orgwise/understanding-your-results/organizational-capacity-assessment
https://sites.google.com/view/orgwise/understanding-your-results/community-capacity-assessment-tool
https://sites.google.com/view/orgwise/understanding-your-results/team-effectiveness-guide

**Comment by gilliankerr** [comment]
The survey respondent should press 'submit' before being taken to these other surveys, rather than 'Next'. Right now there is no signal that they are submitting the results before they are taken to the ending page.

**Comment by mmirasol** [comment]
hello @gilliankerr please confirm where you see Next. I looked at one of the surveys.
Orgwise - Team Effectiveness Guide (ID 837344)
http://logicaloutcomes.net/forms/index.php/837344?newtest=Y
and the last page does show 'Submit' before being taken to 
https://sites.google.com/view/orgwise/result-pages/team-effectiveness-guide
- the above url does not work by the way.

**Comment by gilliankerr** [comment]
The results urls were changed - they are all at https://sites.google.com/view/orgwise/understanding-your-results

**Comment by gilliankerr** [comment]
The Managers Feedback Survey does not have a submit button

**Comment by mmirasol** [comment]
I see.  Fixed it.
![image](https://cloud.githubusercontent.com/assets/13954274/26747739/6e7719dc-482a-11e7-84b7-0a0e42387d61.png)
