### ISSUE TITLE
Setup Admin Notification - Multiple Surveys

### ISSUE THREAD

**Issue by mmirasol** [LogicalOutcomes/SIS-LimeSurvey#18]
Hi Mark - the response receive works!

Can you enable this setting for the 

'LogicalOutcomes Independent Contractor Agreement' survey (my email)

2. and remove from the 

'SIS benchmark' survey (don't need to know about every response for this one)

3. Also enable for these two surveys

DHIS2
 Consultants Registry Sign Up
DHIS2 Consultants Registry Permission

- but use 'DHIS2@logicaloutcomes.net'

4. Delete this survey: Survey DHIS2 Consultants Registry Permission Survey(ID:278139)
(it's a duplicate)

**Comment by mmirasol** [comment]
Can you enable this setting for the
'LogicalOutcomes Independent Contractor Agreement' survey (my email)

**Comment by mmirasol** [comment]
and remove from the
'SIS benchmark' survey (don't need to know about every response for this one)
> don't see a survey named like this.  @saragaudon please confirm.

**Comment by gilliankerr** [comment]
Sara is referring to this survey: Title:	SIS What evaluation services would you like from OCASI? (ID 886367)
Survey URL - English:	http://logicaloutcomes.net/forms/index.php/886367?lang=en

**Comment by mmirasol** [comment]
Also enable for these two surveys
DHIS2 Consultants Registry Sign Up
DHIS2 Consultants Registry Permission
but use 'DHIS2@logicaloutcomes.net' > done.

**Comment by mmirasol** [comment]
@gilliankerr thanks for confirming.
admin notification has been removed from SIS What evaluation services would you like from OCASI?

**Comment by mmirasol** [comment]
Delete this survey: Survey DHIS2 Consultants Registry Permission Survey(ID:278139)
(it's a duplicate) > done.

**Comment by mmirasol** [comment]
@gilliankerr @saragaudon all tasks done. please confirm.

**Comment by gilliankerr** [comment]
@saragaudon I will leave it up to you to review this issue and close it if it's finished.

**Comment by saragaudon** [comment]
Thanks to you both - Mark, I will test the submit/response received later tonight/early tomorrow AM and let you know.

**Comment by saragaudon** [comment]
@mmirasol I added my reply, Editing the comments you left above.

**Comment by mmirasol** [comment]
yes in relation to issue #6 we need to unflag the email as spam in office 365 and test again.  the reason why it's flagged as spam is because it's not going thru smtp but uses the from address: limesurvey@logicaloutcomes.net

**Comment by saragaudon** [comment]
@mmirasol provided smtp for the limesurvey@, let me know if there's more you need here/more testing I can do. I appear to be getting the responses, despite them being flagged as fraud. Yay!

**Comment by mmirasol** [comment]
thanks @saragaudon we successfully sent sms via smtp using my test account.  process currently fails with limesurvey@logicaloutcomes.net with smtp host smtp.office365.com. most likely this is because there is a local domain defined in the webhosting server.

requested @trivender to add smtp.office365.com points to 132.245.69.50 to inmotion's domain settings to make this work.  will retest once this is done.

**Comment by mmirasol** [comment]
@gilliankerr @saragaudon tested the smtp settings for limesurvey@logicaloutcomes.net successfully outside of lime so the troubleshooting that needs to be is on this server.

may i request cpanel access for this?

**Comment by mmirasol** [comment]
@gilliankerr @saragaudon was able to successfully send email using limesurvey@logicaloutcomes.net
bad news however is that because of the domain setup and mx records pointing to office365 it takes around 2 mins before the request is processed because it jumps between 2 webhosts (domain server and office 365) on every request.  
![image](https://cloud.githubusercontent.com/assets/13954274/26748189/110a19bc-482e-11e7-8004-f1a9c088a593.png)

In lime, the end process would timeout within 60 s so the email never gets sent out.

recommendation: use an email from another domain with its mx records set locally. 
this has been tested with gmail. i did the same test with my mail account and i was able to send out within 16s.  
![image](https://cloud.githubusercontent.com/assets/13954274/26748195/1ba0bbb0-482e-11e7-9312-b8af0ffdab34.png)

don't worry too much about the 16 s it takes longer because im printing out the smtp debug. 

as long as we send thru smtp, the email won't be flagged as spam as long as the send volume is low.

**Comment by mmirasol** [comment]
or best would be to park the domain directly on the inmotion server so the email can be sent from the same server as lime.

**Comment by gilliankerr** [comment]
@saragaudon It looks like we should set up an email server in inmotion with logicaloutcomes.ca or logicaloutcomes.org. Do you agree, and if so, which domain would you prefer?

**Comment by saragaudon** [comment]
@mmirasol see my comment on #6 - should we close this thread?

**Comment by mmirasol** [comment]
@saragaudon yes we can continue there.
