### ISSUE TITLE
New User / setting up users in the future 

### ISSUE THREAD

**Issue by saragaudon** [LogicalOutcomes/SIS-LimeSurvey#19]
I need a new user account for Friday if possible:
sbaouji@ocasi.org
Soheil Baouji

Can start having email address as the User login?

This User should ONLY see the 'SIS What evaluation activities....' survey. Nothing else. 

So that we can set up people easily in the future, it would be helpful to be trained on this. I see the LimeSurvey admin guide is available, if there are important points outside of the guide, let me know.

**Comment by mmirasol** [comment]
here you go @saragaudon 
https://manual.limesurvey.org/Manage_users

**Comment by mmirasol** [comment]
using groups you can create roles like data entry, translator, etc so you can specify what tasks he can do.
as for per server access you need to go to the survey and add the user after you create it.
https://manual.limesurvey.org/Manage_users#Setting_permissions_for_a_single_survey

**Comment by saragaudon** [comment]
@mmirasol OR @trivender - I need the authority to create Users. Can either of you provide that authority to me? Thank you.

**Comment by gilliankerr** [comment]
I have done it - you now have full permissions
