### ISSUE TITLE
Remove New Users automatically assigned to all surveys 

### ISSUE THREAD

**Issue by saragaudon** [LogicalOutcomes/SIS-LimeSurvey#20]
@mmirasol is is possible to remove the default that, when a new user is created, they get access to all surveys? Or do you have to go one by one to remove the survey? That's a pain. 
I can see where for each survey, you modify the activities they can perform.

Thanks for your help.

**Comment by mmirasol** [comment]
If you create a user with global permissions to Surveys, the user will see all surveys.  You should create new users only with Use internal database authentication checked.
![image](https://cloud.githubusercontent.com/assets/13954274/26750757/75f7df16-485c-11e7-86d8-a3c4bd3726d8.png)

Then you can assign them to work on specific surveys only.

**Comment by saragaudon** [comment]
Thanks Mark! I've got it, will close this.
