### ISSUE TITLE
Next Step Features List

### ISSUE THREAD

**Issue by mmirasol** [LogicalOutcomes/SIS-LimeSurvey#21]
MARK, THESE CAN BE DONE OVER THE NEXT COUPLE OF DAYS. IF YOU ARE TOO BUSY, YOU DON'T NEED TO MAKE THESE CHANGES.
- [ ] Modify the presentation of the html print answers page - i.e,. narrow the first column, make text left justified instead of centre justified. 

- [ ] Correct Orgwise to OrgWise throughout all surveys (e.g., in the titles and introductions)

**Comment by gilliankerr** [comment]
has this been completed and ready to close?

**Comment by mmirasol** [comment]
Correct Orgwise to OrgWise throughout all surveys - is not done yet.

**Comment by gilliankerr** [comment]
Please close this when finished.
