### ISSUE TITLE
SIS Benchmark survey testing before launch 

### ISSUE THREAD

**Issue by saragaudon** [LogicalOutcomes/SIS-LimeSurvey#22]
@mmirasol where can I enter test participants to receive the email invite we have set up for this survey? (It's a message that appears from OCASI Ddouglas with a link to the survey). You sent this to me last week, I'd like to send the invite to two people for review. 

@saragaudon you can initiate tokens for the survey 
![image](https://cloud.githubusercontent.com/assets/13954274/26801414/6702508a-4a6f-11e7-999f-36c677242c8a.png)

then create tokens for the two people and send the invitation emails.
![image](https://cloud.githubusercontent.com/assets/13954274/26801464/8d465052-4a6f-11e7-963b-165298c09fdb.png)

**Comment by saragaudon** [comment]
Question 1: pick as many options as needed. Right now it's only allowing to select one option. @mmirasol

**Comment by saragaudon** [comment]
Same with Question 2, users can select as many options as they need.

**Comment by saragaudon** [comment]
For Questions 1 & 2, is it possible for the Text box to appear only when the option has been selected? Right now the 'comment' box appears for every option/slightly confusing.

**Comment by saragaudon** [comment]
For Question 3, I need to change the Question options. Where can I do this? Can't seem to find edit options (I see edit question groups).

**Comment by mmirasol** [comment]
Yes it is possible but you would need to break the question into several questions and add an open text after each option so it can be controlled by the checks.  The other way to go about it is to add scripting to the template so it hides the text boxes by default and only show them when checked.

**Comment by saragaudon** [comment]
Looks great Mark, thank you!

**Comment by mmirasol** [comment]
happy to help. =)

**Comment by saragaudon** [comment]
@mmirasol I'm having trouble logging in (ok for now), and also with the Email invite. I modified an English invite, then Saved, now in preview mode there's nothing. I don't have time for this sort of thing, and will need to ask you to check this: there should be an English version of invite that actually includes French because we won't be sending different versions of the invite for different people - every one will get the same email invite.

**Comment by saragaudon** [comment]
![image](https://user-images.githubusercontent.com/15642297/26847979-e9ecf3bc-4acc-11e7-8b08-25b741b0c0e2.png)

**Comment by mmirasol** [comment]
I see content there but it's in French.
![image](https://user-images.githubusercontent.com/13954274/26849732-d9fc2430-4b37-11e7-8e1a-3041343cd890.png)

**Comment by mmirasol** [comment]
can you go in an update it again?

**Comment by saragaudon** [comment]
Hi Mark - sending you an email with the inline images, our French reviewer had a few comments. Please message if this is unclear:

1. In the first french page (where you select language)
The 1st paragraph below title (see image) can be removed as it is similar to what's right below it


2. In the load survey section
In the 3rd line: Replace "Renseignez" with Fournissez


3. In the second question of the survey - Bottom of the frame
 Add at the end of the first sentence: à vous


4. Stats results page:
The title of stats results page shows name of survey in English
And at the bottom of the stats page as well as the print your answers page


5. Finally unlike for the English, at the end of the survey in French (End Message) there is no : LINK TO OCASI INFORMATION PAGE. Can you add a link to the French message that points here: http://ocasi.org/service-information-system-ocasi-member-agencies

**Comment by saragaudon** [comment]
6. The title of the survey that displays on the survey should be just "What evaluation services would you like from OCASI?" Then for French versions, "Quels services d'évaluation souhaiteriez-vous auprès d'OCASI?"


7. Add back the colored hands photo to the main page, like the orgwise surveys...http://www.publicdomainpictures.net/pictures/190000/velka/raised-hands-1471189549xg5.jpg


8. Welcome page needs to be formatted a little better, for example the Confidentiality: should be a heading, with the text falling below it. Let's see how this looks with the picture added, your recommendation here helpful.

**Comment by saragaudon** [comment]
@gilliankerr OCASi translator noticed the MCI footer is in English only. Footer was MCI requirement, not OCASI. Are we ok to keep as-is in English?

**Comment by gilliankerr** [comment]
This must be an OCASI decision

**Comment by mmirasol** [comment]
noted on these issues @saragaudon i have to step out this morning but i will try to be back asap to address them.  you can paste the images directly on github too. just fyi.

**Comment by mmirasol** [comment]
1. In the first french page (where you select language)
The 1st paragraph below title (see image) can be removed as it is similar to what's right below it
I also had centred it on your content system. Not sure if you prefer to be aligned to the left?
![image](https://user-images.githubusercontent.com/13954274/26911267-beaac6d4-4c3e-11e7-8607-173b5d90f577.png)
@saragaudon fixed please check.

2. In the load survey section
![image](https://user-images.githubusercontent.com/13954274/26911283-cf5f1728-4c3e-11e7-9e58-6d9f8be2dd20.png)

In the 3rd line: Replace "Renseignez" with Fournissez
@saragaudon need help finding this. please advise.

3. In the second question of the survey - Bottom of the frame
 Add at the end of the first sentence: à vous
![image](https://user-images.githubusercontent.com/13954274/26911303-f71f37a2-4c3e-11e7-90bb-530e5ee439d9.png)

4. Stats results page:
The title of stats results page shows name of survey in English
![image](https://user-images.githubusercontent.com/13954274/26911311-0709d406-4c3f-11e7-9ae3-26f5d1007306.png)

And at the bottom of the stats page as well as the print your answers page

5. The Funded by / Ontario logo info is also in English
![image](https://user-images.githubusercontent.com/13954274/26911319-13c26f46-4c3f-11e7-95be-fc786bea3e23.png)

6. Finally unlike for the English, at the end of the survey in French there is no : LINK TO OCASI INFORMATION PAGE

**Comment by mmirasol** [comment]
For items 4 and 5 will check if that's possible cos the template doesn't break it down. will need to check with lime support on that.

**Comment by mmirasol** [comment]
For items 6, 7 and 8,
this is because we are using the welcome page.
we can just disable it on the survey settings (see below) and set relevance = 1 for the start page so we can use that one instead. that's where the image is.
![image](https://user-images.githubusercontent.com/13954274/26941689-f11a95d6-4cb1-11e7-844f-091a92cd385b.png)
![image](https://user-images.githubusercontent.com/13954274/26941703-fdac2936-4cb1-11e7-9182-7c524f87cb21.png)

**Comment by saragaudon** [comment]
As per Gillian's suggestion, let's bring back the image on the welcome page for the SIS benchmark.


Everything else is fine Mark, thank you!

Sara

---
Sara Gaudon, Executive Director, LogicalOutcomes<http://www.logicaloutcomes.net/>
sara@logicaloutcomes.net<http://www.logicaloutcomes.net/> | Toronto 647-478-5634 x103 Washington 202-779-9634 x103

________________________________

**Comment by mmirasol** [comment]
ok will take care of it.

**Comment by saragaudon** [comment]
@mmirasol client is asking, when the survey is viewed in French, if the Footer can also be in French. Is this theme switch possible? OR should we make a bi-lingual footer that has both English and French sentences?

**Comment by gilliankerr** [comment]
@saragaudon when this issue is closed, can we delete the whole repo? I guesss we should download and archive it for reference?
