### ISSUE TITLE
Minor corrections needed for OrgWise surveys

### ISSUE THREAD

**Issue by traciwilson** [LogicalOutcomes/SIS-LimeSurvey#24]
@mmirasol @gilliankerr I've reviewed the first 5 surveys, and made minor changes where it didn't involve deactivating the survey.

There are some minor fixes needed to questions on Governance and legal structure module. I can do them tomorrow if Mark is unable to today. Tomorrow I will also review the other 6 surveys.

Governance and legal structure
Is the organization legally registered? What legal registration does the organization have? When was it registered? When does the registration expire? Are there any risks to renewal of the registration?

**Fix**: The organization has legally registered and is in fully compliance with all required permits and licenses - [fix "is in full compliance"]

Fix: The organization has a charter, constitution,or by-laws that are updated as needed
[spacing issues]

Fix: The organization has inadequate knowledge or is unaware of all permits or licenses required foroperation or has not applied for them
[spacing issues]

Fix: Add u in labor: Is the organization aware of national and local tax, labor, occupational health and safety, and environmental laws?
[change to "labour" in question and answers]

Fix: The organization has pending legal actions orownership changes may jeopardize operations
[spacing issues]

Duplicate answers:
Is there a documented organizational chart or structure? Is the organizational structure appropriate for current programs? Does it support clear direction for staff?

Is the organizational structure updated as needed? When was it last revised?

Combine these questions to read: Is there a documented organizational chart or structure? Is it followed and updated as needed?

This question needs to be refined.:
What is the full size of the board? How many board members have joined within the past year? Are board members drawn from a broad spectrum (gender, ethnic, religious, and age)? Are board appointments and terms transparent and appropriate?

Succession planning
Are changes in the leadership expected over the next two years?
-Change to text box and delete answers (which are a duplicate of another question)

**Comment by gilliankerr** [comment]
Wonderful, thanks. I've sent off the invitations and my first interview is tomorrow; keep making those revisions because the interviews will be over the next 2 weeks and we can tweak throughout.

**Comment by gilliankerr** [comment]
I'm closing this issue.
