### ISSUE TITLE
SIS benchmark new survey changes from OCASI

### ISSUE THREAD

**Issue by saragaudon** [LogicalOutcomes/SIS-LimeSurvey#25]
1. Replace the image with this one 
http://www.publicdomainpictures.net/pictures/190000/velka/raised-hands-1471189549xg5.jp
@saragaudon the link above does not work. 

2. Edit the survey title that appear in the survey, "Sector Evaluation Needs and Activities"
@saragaudon done. 

3. Please replace this header 'What are you doing now?'
with
"What evaluation activities are you doing right now?"
@saragaudon done.

4. Replace this header ' What role would you like?'
with
 "In what capacity would you like to be involved in this evaluation project? Check as many as apply.
@saragaudon done.

5. To this question ('how would you like to be involved...'), add one more option: 
"My organization cannot be actively involved in this evaluation project at this point but I would like to stay informed of progress"
@saragaudon done.
 
6.  Add the following open text question to the survey ( new question)
 
"What are the challenges you have experienced as you engaged in carrying out evaluation activities at your organization?"
@saragaudon should we add this to the last group or create a new group before it?

**Comment by mmirasol** [comment]
@saragaudon noted on your requests. will let you know once done.

**Comment by mmirasol** [comment]
@saragaudon here's the test link.
http://logicaloutcomes.net/forms/index.php/886367?newtest=Y

**Comment by saragaudon** [comment]
Thanks @mmirasol 
1. the picture was missing a g: http://www.publicdomainpictures.net/pictures/190000/velka/raised-hands-1471189549xg5.jpg
2. add a separate page for the 'what challenges have you experienced with current evaluations?' - I'd like this question to come before the 'How would you like to participate in this project' question

The last page will have the 'anything else' question + select agency.

**Comment by mmirasol** [comment]
@saragaudon changes complete. please check.
http://logicaloutcomes.net/forms/index.php/886367?newtest=Y

**Comment by saragaudon** [comment]
@mmirasol  

1. make the title 'Evaluation challenges' for that question (not 'what challenges')

On the post-submit page
2.  can you make the 'View Statistics' font bigger, so that's what people are encouraged to click?

3. Remove the 'OCASI INFORMAITON PAGE' - this is the same as the link that's already listed. 
![image](https://user-images.githubusercontent.com/15642297/27548129-fc84536e-5a65-11e7-9ea0-fca69bb56295.png)

**Comment by mmirasol** [comment]
@saragaudon please check again.
http://logicaloutcomes.net/forms/index.php/886367?newtest=Y&lang=en

**Comment by saragaudon** [comment]
@mmirasol in French version, please change the image - I think it's saving the cartoon ladies from English version. Otherwise, client is happy!

**Comment by saragaudon** [comment]
Thanks @mmirasol can you remove all submissions? We should be going live shortly!

**Comment by mmirasol** [comment]
@saragaudon done.

**Comment by saragaudon** [comment]
@mmirasol can you add one organization to that big drop down / the last questions?  It's "Madison Community Services"

**Comment by mmirasol** [comment]
@saragaudon done.
![image](https://user-images.githubusercontent.com/13954274/27841531-f071c86a-6134-11e7-9fe3-1c9794bc2298.png)

**Comment by saragaudon** [comment]
Thanks @mmirasol - can you remove the user Kaye Fox completely from the LimeSurvey system? No user account is needed. Thank you.
