### ISSUE TITLE
Create  LogicalOutcomes branded theme and assign to selected surveys

### ISSUE THREAD

**Issue by gilliankerr** [LogicalOutcomes/SIS-LimeSurvey#5]
DUE: June 3
1. Create a new template from 'tfr responsive lo' with dark blue instead of dark green, and with only the LogicalOutcomes logo, not OCASI. LogicalOutcomes logo should be on the left. 

2. Assign the following surveys to this template: 
- the ones starting with DHIS2 
- the ones starting with LogicalOutcomes

Updated Instructions (6/1/2017):
Logo should be in line with the left side of the blue bar, and the footer should be removed, and the picture should be switched with the image with the hands

Additional Comments:
we will have 2 templates: 1. For SIS/OCASI 2.For LogicalOutcomes/DHIS2 consultants list

**Comment by gilliankerr** [comment]
Trivender, let me know if you need more details

**Comment by trivender** [comment]
Once template is approved in this test link I will add it surveys you mentioned.
http://logicaloutcomes.net/forms/index.php/667418?lang=en

**Comment by gilliankerr** [comment]
1. Please move the logo left, in line with the beginning of the blue bar. 
2. Remove footer image: 
![image](https://cloud.githubusercontent.com/assets/4176201/26558625/49d83c42-4478-11e7-8d7c-6005a6b5882b.png)

3. replace the current image with this one http://www.publicdomainpictures.net/pictures/190000/velka/raised-hands-1471189549xg5.jpg

4. Replace text with the following:

***

This is draft content. You can change the image also. 

Number of questions : 14
Time to complete : 5 minutes

**Comment by gilliankerr** [comment]
Great thanks

**Comment by gilliankerr** [comment]
Whoops, I closed this in error.

**Comment by saragaudon** [comment]
Mark is working on the template also; he added a progress bar and welcome page (see Other Issue on this)...

**Comment by trivender** [comment]
What other issue? I guess you can link issues here.

**Comment by gilliankerr** [comment]
My fault, this seems to have multiple assignees. I have reassigned this to Mark, since he is working with another set of surveys directly with Sara. Sara, please take over as the lead on this and my apologies for confusion.

**Comment by mmirasol** [comment]
hello @gilliankerr @saragaudon @trivender i did not work on this template specifically. i added the progress bar to tfr_lo_oc. since trivender already started working on this would suggest we let him complete his requests first. he can always integrated the changes from the other template.

@trivender what do you think?

**Comment by mmirasol** [comment]
this is the other issue #13

**Comment by mmirasol** [comment]
Updated Instructions (6/1/2017):
Logo should be in line with the left side of the blue bar, and the footer should be removed, and the picture should be switched with the image with the hands

changes complete.
@gilliankerr @saragaudon please check.
http://logicaloutcomes.net/forms/index.php/667418?newtest=Y

**Comment by gilliankerr** [comment]
This template looks great. @saragaudon do you want any other changes to the LogicalOutcomes template? If not, @mmirasol should assign the following surveys to this template:

the ones starting with DHIS2
the ones starting with LogicalOutcomes

**Comment by saragaudon** [comment]
Hi all - Mark has made the changes to progress bar, we have to themes! an OCASI green theme, and LO blue theme. Thanks Mark.

**Comment by mmirasol** [comment]
happy to help.
we have renamed the green and blue themes as OCASI-standard and LO-standard as per gillian's advise.
