### ISSUE TITLE
Set up user permissions 

### ISSUE THREAD

**Issue by gilliankerr** [LogicalOutcomes/SIS-LimeSurvey#7]
DUE WEDNESDAY:
Give the following users permissions to view, edit and create surveys if they do not already have them:
jasleen@logicaloutcomes.net Jasleen Kaur
moiz@logicaloutcomes.net Moiz Badhani
gillian@logicaloutcomes.net Gillian Kerr
sara@logicaloutcomes.net  Sara Gaudon
rafael@logicaloutcomes.net Rafael Capdevielle

Set up user account for Kaye Fookson  kaye@logicaloutcomes.net and give her view and edit permissions on surveys
Ensure that emails are going out to new users (check smtp settings - see related issue)

Advise Gillian on what kinds of permissions should be given to different users.

**Comment by trivender** [comment]
As we are facing some concerns in receiving email to logicaloutcomes domain so I set passwords as well. Respective login details are in below pattern.
Username: Firstname
Pass: Firstname@123

**Comment by gilliankerr** [comment]
Please provide the URL for changing passwords, I can't see how to change my password in this version of Limesurvey

**Comment by gilliankerr** [comment]
FOR NEXT MONDAY: Once we get the outgoing emails figured out, please create new usernames using the email addresses, not the first names, and email everyone a unique password. All usernames should follow the convention of name@logicaloutcomes.net.
