### ISSUE TITLE
Assign SIS survey to the OrgWise template

### ISSUE THREAD

**Issue by gilliankerr** [LogicalOutcomes/SIS-LimeSurvey#8]
DUE: Monday
Assign this survey to the OrgWise template: 
"SIS What evaluation services would you like from OCASI?"

**Comment by trivender** [comment]
Where is this survey. Surveys currently at /forms
![image](https://cloud.githubusercontent.com/assets/1558981/26549507/05ae2710-4497-11e7-84d6-283fa4fb777f.png)

**Comment by gilliankerr** [comment]
Did you transfer the two surveys on page 2 http://logicaloutcomes.net/survey/index.php/admin/survey/sa/listsurveys

[cid:image003.png@01D2D855.DE4D3FB0]

--
Dr. Gillian Kerr, C.Psych | President, LogicalOutcomes | Toronto (416) 531-7634 | Washington DC (202) 779-9634 ext 101 | Skype ID: gilliankerr | gillian(at)logicaloutcomes.net | Book a meeting with me at https://logicaloutcomes.acuityscheduling.com/schedule.php?appointmentType=category:Meeting+with+Gillian+Kerr

**Comment by trivender** [comment]
Test link: http://logicaloutcomes.net/forms/index.php/886367?lang=en . I noticed this survey has french language added but not translated. Are we going to run this survey in french or it is accidentally added?

**Comment by gilliankerr** [comment]
Yes, it will be run in French, and we are waiting for translation.
