### ISSUE TITLE
Change name of this repo to SIS-LimeSurvey

### ISSUE THREAD

**Issue by gilliankerr** [LogicalOutcomes/SIS-LimeSurvey#9]
Rafael, can we change the name of this repo or is it easier to create a new one and just close this one? We are making all kinds of changes to the limesurvey templates and it goes beyond the ocasi template. 
For example, we are changing to an older version of limesurvey (v 2.06) that is more stable, which means using another theme....

**Comment by rafen** [comment]
@gilliankerr yes we can change. I will do it.

**Comment by gilliankerr** [comment]
OK great - then we will send people the updated URL.

**Comment by rafen** [comment]
changed!
